name: Build

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            build-essential \
            cmake \
            libgit2-dev \
            libcli11-dev \
            libtomlplusplus-dev

      - name: Configure CMake
        run: cmake -S. -Bbuild

      - name: Build project
        run: cmake --build build -j$(nproc)

      # note: this uploads a dynamic executable, so systems you run it on need our dependencies installed.
      # if we want, we can also build a static executable to avoid the above problem.
      # this will take more build system work, though.
      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: dotplug
          path: |
            build/dotplug
